version: '2'
services:
  db:
    image: postgres:15.0
    container_name: db
    environment:
      - POSTGRES_DB=public
      - POSTGRES_USER=hector
      - POSTGRES_PASSWORD=1234
      - PGDATA=/var/lib/pgsql_docker/data
    volumes:
      - ./src/main/resources/db/postgres/V1__create_user_table.sql:/docker-entrypoint-initdb.d/V1__create_user_table.sql
    ports:
      - "5432:5432"
    networks:
      - database-network
  web:
    image: "micronaut-prueba:latest"
    container_name: web
    build: ./
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/public
      - JDBC_USER=hector
      - JDBC_PASSWORD=1234
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - database-network
      - internal
networks:
  database-network:
  internal: