micronaut:
  server:
    port: 8080
  application:
    name: pruebaTecnica
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/public`}
    username: ${JDBC_USER:hector}
    password: ${JDBC_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    hikari:
      pool-name: postgresql-pool
      minimum-idle: 2
      maximum-pool-size: 5
jooq:
  datasources:
    default:
      sql-dialect: 'POSTGRES'
jpa:
  default:
    entity-scan:
      classpath: true
      packages:
        - 'com.prueba.repository.model'
netty:
  default:
    allocator:
      max-order: 3
