/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.Arrays;
import java.util.List;

import jooq.tables.Alumnos;
import jooq.tables.Calificaciones;
import jooq.tables.FlywaySchemaHistory;
import jooq.tables.Materias;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.alumnos</code>.
     */
    public final Alumnos ALUMNOS = Alumnos.ALUMNOS;

    /**
     * The table <code>public.calificaciones</code>.
     */
    public final Calificaciones CALIFICACIONES = Calificaciones.CALIFICACIONES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.materias</code>.
     */
    public final Materias MATERIAS = Materias.MATERIAS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Alumnos.ALUMNOS,
            Calificaciones.CALIFICACIONES,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Materias.MATERIAS
        );
    }
}
