/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Alumnos;
import jooq.tables.Calificaciones;
import jooq.tables.FlywaySchemaHistory;
import jooq.tables.Materias;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.alumnos</code>.
     */
    public static final Alumnos ALUMNOS = Alumnos.ALUMNOS;

    /**
     * The table <code>public.calificaciones</code>.
     */
    public static final Calificaciones CALIFICACIONES = Calificaciones.CALIFICACIONES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.materias</code>.
     */
    public static final Materias MATERIAS = Materias.MATERIAS;
}
