/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import jooq.tables.Calificaciones;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "calificaciones",
    schema = "public"
)
public class CalificacionesRecord extends UpdatableRecordImpl<CalificacionesRecord> implements Record6<Integer, Integer, Integer, Boolean, LocalDateTime, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.calificaciones.id_calificacion</code>.
     */
    public CalificacionesRecord setIdCalificacion(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.calificaciones.id_calificacion</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_calificacion", nullable = false, precision = 32)
    public Integer getIdCalificacion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.calificaciones.id_materia</code>.
     */
    public CalificacionesRecord setIdMateria(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.calificaciones.id_materia</code>.
     */
    @Column(name = "id_materia", nullable = false, precision = 32)
    @NotNull
    public Integer getIdMateria() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.calificaciones.id_alumno</code>.
     */
    public CalificacionesRecord setIdAlumno(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.calificaciones.id_alumno</code>.
     */
    @Column(name = "id_alumno", nullable = false, precision = 32)
    @NotNull
    public Integer getIdAlumno() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.calificaciones.activo</code>.
     */
    public CalificacionesRecord setActivo(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.calificaciones.activo</code>.
     */
    @Column(name = "activo", nullable = false)
    public Boolean getActivo() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.calificaciones.fecha_registro</code>.
     */
    public CalificacionesRecord setFechaRegistro(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.calificaciones.fecha_registro</code>.
     */
    @Column(name = "fecha_registro", precision = 6)
    public LocalDateTime getFechaRegistro() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.calificaciones.calificacion</code>.
     */
    public CalificacionesRecord setCalificacion(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.calificaciones.calificacion</code>.
     */
    @Column(name = "calificacion", precision = 10, scale = 2)
    public BigDecimal getCalificacion() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, Boolean, LocalDateTime, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, Boolean, LocalDateTime, BigDecimal> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Calificaciones.CALIFICACIONES.ID_CALIFICACION;
    }

    @Override
    public Field<Integer> field2() {
        return Calificaciones.CALIFICACIONES.ID_MATERIA;
    }

    @Override
    public Field<Integer> field3() {
        return Calificaciones.CALIFICACIONES.ID_ALUMNO;
    }

    @Override
    public Field<Boolean> field4() {
        return Calificaciones.CALIFICACIONES.ACTIVO;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Calificaciones.CALIFICACIONES.FECHA_REGISTRO;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Calificaciones.CALIFICACIONES.CALIFICACION;
    }

    @Override
    public Integer component1() {
        return getIdCalificacion();
    }

    @Override
    public Integer component2() {
        return getIdMateria();
    }

    @Override
    public Integer component3() {
        return getIdAlumno();
    }

    @Override
    public Boolean component4() {
        return getActivo();
    }

    @Override
    public LocalDateTime component5() {
        return getFechaRegistro();
    }

    @Override
    public BigDecimal component6() {
        return getCalificacion();
    }

    @Override
    public Integer value1() {
        return getIdCalificacion();
    }

    @Override
    public Integer value2() {
        return getIdMateria();
    }

    @Override
    public Integer value3() {
        return getIdAlumno();
    }

    @Override
    public Boolean value4() {
        return getActivo();
    }

    @Override
    public LocalDateTime value5() {
        return getFechaRegistro();
    }

    @Override
    public BigDecimal value6() {
        return getCalificacion();
    }

    @Override
    public CalificacionesRecord value1(Integer value) {
        setIdCalificacion(value);
        return this;
    }

    @Override
    public CalificacionesRecord value2(Integer value) {
        setIdMateria(value);
        return this;
    }

    @Override
    public CalificacionesRecord value3(Integer value) {
        setIdAlumno(value);
        return this;
    }

    @Override
    public CalificacionesRecord value4(Boolean value) {
        setActivo(value);
        return this;
    }

    @Override
    public CalificacionesRecord value5(LocalDateTime value) {
        setFechaRegistro(value);
        return this;
    }

    @Override
    public CalificacionesRecord value6(BigDecimal value) {
        setCalificacion(value);
        return this;
    }

    @Override
    public CalificacionesRecord values(Integer value1, Integer value2, Integer value3, Boolean value4, LocalDateTime value5, BigDecimal value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CalificacionesRecord
     */
    public CalificacionesRecord() {
        super(Calificaciones.CALIFICACIONES);
    }

    /**
     * Create a detached, initialised CalificacionesRecord
     */
    public CalificacionesRecord(Integer idCalificacion, Integer idMateria, Integer idAlumno, Boolean activo, LocalDateTime fechaRegistro, BigDecimal calificacion) {
        super(Calificaciones.CALIFICACIONES);

        setIdCalificacion(idCalificacion);
        setIdMateria(idMateria);
        setIdAlumno(idAlumno);
        setActivo(activo);
        setFechaRegistro(fechaRegistro);
        setCalificacion(calificacion);
    }

    /**
     * Create a detached, initialised CalificacionesRecord
     */
    public CalificacionesRecord(jooq.tables.pojos.Calificaciones value) {
        super(Calificaciones.CALIFICACIONES);

        if (value != null) {
            setIdCalificacion(value.getIdCalificacion());
            setIdMateria(value.getIdMateria());
            setIdAlumno(value.getIdAlumno());
            setActivo(value.getActivo());
            setFechaRegistro(value.getFechaRegistro());
            setCalificacion(value.getCalificacion());
        }
    }
}
