/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;

import jooq.tables.Materias;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "materias",
    schema = "public"
)
public class MateriasRecord extends UpdatableRecordImpl<MateriasRecord> implements Record3<Integer, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.materias.id_materia</code>.
     */
    public MateriasRecord setIdMateria(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.materias.id_materia</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_materia", nullable = false, precision = 32)
    public Integer getIdMateria() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.materias.nombre</code>.
     */
    public MateriasRecord setNombre(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.materias.nombre</code>.
     */
    @Column(name = "nombre", length = 80)
    @Size(max = 80)
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.materias.activo</code>.
     */
    public MateriasRecord setActivo(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.materias.activo</code>.
     */
    @Column(name = "activo", nullable = false)
    public Boolean getActivo() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Materias.MATERIAS.ID_MATERIA;
    }

    @Override
    public Field<String> field2() {
        return Materias.MATERIAS.NOMBRE;
    }

    @Override
    public Field<Boolean> field3() {
        return Materias.MATERIAS.ACTIVO;
    }

    @Override
    public Integer component1() {
        return getIdMateria();
    }

    @Override
    public String component2() {
        return getNombre();
    }

    @Override
    public Boolean component3() {
        return getActivo();
    }

    @Override
    public Integer value1() {
        return getIdMateria();
    }

    @Override
    public String value2() {
        return getNombre();
    }

    @Override
    public Boolean value3() {
        return getActivo();
    }

    @Override
    public MateriasRecord value1(Integer value) {
        setIdMateria(value);
        return this;
    }

    @Override
    public MateriasRecord value2(String value) {
        setNombre(value);
        return this;
    }

    @Override
    public MateriasRecord value3(Boolean value) {
        setActivo(value);
        return this;
    }

    @Override
    public MateriasRecord values(Integer value1, String value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MateriasRecord
     */
    public MateriasRecord() {
        super(Materias.MATERIAS);
    }

    /**
     * Create a detached, initialised MateriasRecord
     */
    public MateriasRecord(Integer idMateria, String nombre, Boolean activo) {
        super(Materias.MATERIAS);

        setIdMateria(idMateria);
        setNombre(nombre);
        setActivo(activo);
    }

    /**
     * Create a detached, initialised MateriasRecord
     */
    public MateriasRecord(jooq.tables.pojos.Materias value) {
        super(Materias.MATERIAS);

        if (value != null) {
            setIdMateria(value.getIdMateria());
            setNombre(value.getNombre());
            setActivo(value.getActivo());
        }
    }
}
