/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import jooq.tables.Calificaciones;
import jooq.tables.records.CalificacionesRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CalificacionesDao extends DAOImpl<CalificacionesRecord, jooq.tables.pojos.Calificaciones, Integer> {

    /**
     * Create a new CalificacionesDao without any configuration
     */
    public CalificacionesDao() {
        super(Calificaciones.CALIFICACIONES, jooq.tables.pojos.Calificaciones.class);
    }

    /**
     * Create a new CalificacionesDao with an attached configuration
     */
    public CalificacionesDao(Configuration configuration) {
        super(Calificaciones.CALIFICACIONES, jooq.tables.pojos.Calificaciones.class, configuration);
    }

    @Override
    public Integer getId(jooq.tables.pojos.Calificaciones object) {
        return object.getIdCalificacion();
    }

    /**
     * Fetch records that have <code>id_calificacion BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchRangeOfIdCalificacion(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Calificaciones.CALIFICACIONES.ID_CALIFICACION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id_calificacion IN (values)</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchByIdCalificacion(Integer... values) {
        return fetch(Calificaciones.CALIFICACIONES.ID_CALIFICACION, values);
    }

    /**
     * Fetch a unique record that has <code>id_calificacion = value</code>
     */
    public jooq.tables.pojos.Calificaciones fetchOneByIdCalificacion(Integer value) {
        return fetchOne(Calificaciones.CALIFICACIONES.ID_CALIFICACION, value);
    }

    /**
     * Fetch a unique record that has <code>id_calificacion = value</code>
     */
    public Optional<jooq.tables.pojos.Calificaciones> fetchOptionalByIdCalificacion(Integer value) {
        return fetchOptional(Calificaciones.CALIFICACIONES.ID_CALIFICACION, value);
    }

    /**
     * Fetch records that have <code>id_materia BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchRangeOfIdMateria(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Calificaciones.CALIFICACIONES.ID_MATERIA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id_materia IN (values)</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchByIdMateria(Integer... values) {
        return fetch(Calificaciones.CALIFICACIONES.ID_MATERIA, values);
    }

    /**
     * Fetch records that have <code>id_alumno BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchRangeOfIdAlumno(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Calificaciones.CALIFICACIONES.ID_ALUMNO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id_alumno IN (values)</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchByIdAlumno(Integer... values) {
        return fetch(Calificaciones.CALIFICACIONES.ID_ALUMNO, values);
    }

    /**
     * Fetch records that have <code>activo BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchRangeOfActivo(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Calificaciones.CALIFICACIONES.ACTIVO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>activo IN (values)</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchByActivo(Boolean... values) {
        return fetch(Calificaciones.CALIFICACIONES.ACTIVO, values);
    }

    /**
     * Fetch records that have <code>fecha_registro BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchRangeOfFechaRegistro(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Calificaciones.CALIFICACIONES.FECHA_REGISTRO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fecha_registro IN (values)</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchByFechaRegistro(LocalDateTime... values) {
        return fetch(Calificaciones.CALIFICACIONES.FECHA_REGISTRO, values);
    }

    /**
     * Fetch records that have <code>calificacion BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchRangeOfCalificacion(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Calificaciones.CALIFICACIONES.CALIFICACION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>calificacion IN (values)</code>
     */
    public List<jooq.tables.pojos.Calificaciones> fetchByCalificacion(BigDecimal... values) {
        return fetch(Calificaciones.CALIFICACIONES.CALIFICACION, values);
    }
}
