/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;
import java.util.Optional;

import jooq.tables.Materias;
import jooq.tables.records.MateriasRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MateriasDao extends DAOImpl<MateriasRecord, jooq.tables.pojos.Materias, Integer> {

    /**
     * Create a new MateriasDao without any configuration
     */
    public MateriasDao() {
        super(Materias.MATERIAS, jooq.tables.pojos.Materias.class);
    }

    /**
     * Create a new MateriasDao with an attached configuration
     */
    public MateriasDao(Configuration configuration) {
        super(Materias.MATERIAS, jooq.tables.pojos.Materias.class, configuration);
    }

    @Override
    public Integer getId(jooq.tables.pojos.Materias object) {
        return object.getIdMateria();
    }

    /**
     * Fetch records that have <code>id_materia BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Materias> fetchRangeOfIdMateria(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Materias.MATERIAS.ID_MATERIA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id_materia IN (values)</code>
     */
    public List<jooq.tables.pojos.Materias> fetchByIdMateria(Integer... values) {
        return fetch(Materias.MATERIAS.ID_MATERIA, values);
    }

    /**
     * Fetch a unique record that has <code>id_materia = value</code>
     */
    public jooq.tables.pojos.Materias fetchOneByIdMateria(Integer value) {
        return fetchOne(Materias.MATERIAS.ID_MATERIA, value);
    }

    /**
     * Fetch a unique record that has <code>id_materia = value</code>
     */
    public Optional<jooq.tables.pojos.Materias> fetchOptionalByIdMateria(Integer value) {
        return fetchOptional(Materias.MATERIAS.ID_MATERIA, value);
    }

    /**
     * Fetch records that have <code>nombre BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Materias> fetchRangeOfNombre(String lowerInclusive, String upperInclusive) {
        return fetchRange(Materias.MATERIAS.NOMBRE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>nombre IN (values)</code>
     */
    public List<jooq.tables.pojos.Materias> fetchByNombre(String... values) {
        return fetch(Materias.MATERIAS.NOMBRE, values);
    }

    /**
     * Fetch records that have <code>activo BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Materias> fetchRangeOfActivo(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Materias.MATERIAS.ACTIVO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>activo IN (values)</code>
     */
    public List<jooq.tables.pojos.Materias> fetchByActivo(Boolean... values) {
        return fetch(Materias.MATERIAS.ACTIVO, values);
    }
}
