/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "materias",
    schema = "public"
)
public class Materias implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer idMateria;
    private String  nombre;
    private Boolean activo;

    public Materias() {}

    public Materias(Materias value) {
        this.idMateria = value.idMateria;
        this.nombre = value.nombre;
        this.activo = value.activo;
    }

    public Materias(
        Integer idMateria,
        String  nombre,
        Boolean activo
    ) {
        this.idMateria = idMateria;
        this.nombre = nombre;
        this.activo = activo;
    }

    /**
     * Getter for <code>public.materias.id_materia</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_materia", nullable = false, precision = 32)
    public Integer getIdMateria() {
        return this.idMateria;
    }

    /**
     * Setter for <code>public.materias.id_materia</code>.
     */
    public Materias setIdMateria(Integer idMateria) {
        this.idMateria = idMateria;
        return this;
    }

    /**
     * Getter for <code>public.materias.nombre</code>.
     */
    @Column(name = "nombre", length = 80)
    @Size(max = 80)
    public String getNombre() {
        return this.nombre;
    }

    /**
     * Setter for <code>public.materias.nombre</code>.
     */
    public Materias setNombre(String nombre) {
        this.nombre = nombre;
        return this;
    }

    /**
     * Getter for <code>public.materias.activo</code>.
     */
    @Column(name = "activo", nullable = false)
    public Boolean getActivo() {
        return this.activo;
    }

    /**
     * Setter for <code>public.materias.activo</code>.
     */
    public Materias setActivo(Boolean activo) {
        this.activo = activo;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Materias (");

        sb.append(idMateria);
        sb.append(", ").append(nombre);
        sb.append(", ").append(activo);

        sb.append(")");
        return sb.toString();
    }
}
